import Head from "next/head";
import styles from "../styles/components/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <h1>Nextjs portfolio</h1>
        </div>
      </main>
    </>
  );
}
