import Head from "next/head";
import styles from "../styles/components/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Nextjs portfolio</h1>
      </main>
    </div>
  );
}
